### ISSUE TITLE
Bread Recipe - Natura bypasses PAMS

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#10]
**Describe the bug**
Recipe that bypasses PAMS in the form of
-Wheat straight craft into flour
-flour cooked in furnace

**Expected behavior**
Recipe for bread is only/mainly through the PAMs tools

**Screenshots**
![image](https://user-images.githubusercontent.com/97805739/158505075-89b9fbd7-eb7c-42f3-8697-657bac254868.png)
![image](https://user-images.githubusercontent.com/97805739/158505096-5134e172-8071-45e3-bbe7-6c326ff4fa5f.png)

**Clientside information (please complete the following information):**
 - Düncraft Version [031222a]

**Comment by Pingu-Pox** [comment]
Removed bread furnace recipes, bread must be made through harvestcraft. Also changed dough recipe to reference correct ingredients.

Available in next update.
