### ISSUE TITLE
PAMs Salt recipe consumes water container

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#11]
**Describe the bug**
The PAMs recipe to make salt is to combine pot + [water bucket/Fresh Water (11226)/water bottle] but it consumes and destroys the container in the process.

**To Reproduce**
![image](https://user-images.githubusercontent.com/97805739/158508969-6b1ddcb8-8cd2-4bf2-9430-f67a14af7d37.png)

**Expected behavior**
Recipe keeps empty container in crafting. ie the vanilla cake recipe takes bucket of milk but leaves empty bucket.

**Clientside information (please complete the following information):**
 - Düncraft Version [031222a]

**Additional context**
Only tested the crafting with the water bottle and Fresh Water (11226). Did not test with water bucket.

**Comment by Pingu-Pox** [comment]
Removed the salt recipes, re-added them with item return functions performed on the pot and water containers.

Fixed in next verison.
