### ISSUE TITLE
PAMs Fresh Water item has a duplication recipe

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#12]
**Describe the bug**
PAMs has a Fresh Water (11226) that is made by single crafting a bucket of water or water bottle. This recipe destroys the container and gives 8 copies of the Fresh water item. If you then place the Fresh Water item in crafting it uses 1 to make another 8.

**To Reproduce**
![image](https://user-images.githubusercontent.com/97805739/158509373-95ed2615-5c3d-45fe-9b2a-cc8a127d68ed.png)

**Expected behavior**
This recipe really shouldn't exist

**Clientside information (please complete the following information):**
 - Düncraft Version [031222a]

**Comment by Pingu-Pox** [comment]
Removed all crafting recipes for <harvestcraft:freshwateritem>, and made a switch-recipe between <harvestcraft:freshwateritem> and <simpledifficulty:purified_water_bottle>

Coming in next update.
