### ISSUE TITLE
Wooden Trapdoor Recipe - Can only swap Oak Trapdoor

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#13]
**Describe the bug**
The vanilla and conquest recipes for trapdoor overlap and default to the conquest version. Recipes that require a trapdoor are thus unable to be crafted. I believe a fix was added to allow swapping between the 2 forms, but this swap recipe appears to only work for vanilla oak trapdoor and conquest oak trapdoor.

**To Reproduce**
Attempt to craft a trapdoor out of a wood other than vanilla oak. You get conquest trapdoor without the option to swap.

**Screenshots**
Oak trapdoor
![image](https://user-images.githubusercontent.com/97805739/158674086-181867ef-0de7-4d22-9e3d-e3e42cb0ecdd.png)
Acacia trapdoor
![image](https://user-images.githubusercontent.com/97805739/158674014-a066b6cd-f013-453d-95cc-6928423fe7b8.png)

**Clientside information (please complete the following information):**
 - Düncraft Version [031222a]

**Comment by Pingu-Pox** [comment]
To be clear, you want to be able to take conquest's other trap doors, and convert them to the vanilla trapdoor? Right?

**Comment by Halfshot555** [comment]
Yes, in the case of what initiated this ticket; I was trying to make trap doors for the wopper recipe (removed, but other recipes call for trapdoor too) and the only wood we had readily available was something other than oak. (Either acacia or forestry lime I forget) When trying to craft trap doors though, it gave their conquest variant with no way to convert to a standard trapdoor. To resolve at the time was to tear down a wall of the village to make oak trapdoors.

**Comment by Pingu-Pox** [comment]
Make a custom trapdoor oreDict. If any recipes that call for a trapdoor do not take ANY trapdoor, report it to me. Idk if this issue is even valid anymore, but I wanted a more complete answer than using swapping recipes.
