### ISSUE TITLE
Level Up Reloaded - Furnace skill overlaps with block pickup

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#14]
**Describe the bug**
The furnace cook speed skill in Level Up Reloaded uses the [Shift]+[Right Click] that is also used to pickup blocks. This causes the skill to be unusable.

**Screenshots**
![image](https://user-images.githubusercontent.com/97805739/158683095-a8602dc5-7253-49d9-84a6-018cec59c51e.png)

**Clientside information (please complete the following information):**
 - Düncraft Version [031222a]

**Comment by Pingu-Pox** [comment]
Fixed in next version
