### ISSUE TITLE
Tinker's Pickaxe not dropping Stone

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#15]
**Describe the bug**
Crafted multiple Tinker's Copper pickaxes and they are not dropping stone blocks. It is breaking with the expected speed and tooltip shows that its a valid tool, but no item is dropped. Breaking same stone blocks with vanilla stone pickaxe gives drops.

Vanilla Granite [Fail]
Conquest Rough Natural Sandstone [Fail]
Vanilla Cobblestone [Works]
Forestry Apatite [Works]

**Clientside information (please complete the following information):**
 - Düncraft Version [031222a]

**Comment by Pingu-Pox** [comment]
Known issue that will not be fixed.
https://github.com/Conquest-Reforged/ConquestReforged/issues/107
