### ISSUE TITLE
Agricraft Crop Sticks regrow too fast

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#16]
**Describe the bug**
Plants growing in Crop Sticks are regrowing after harvesting in less than a minute.

**Expected behavior**
Crop sticks growing slightly faster might be acceptable, but less than a minute to regrow is too much.

**Clientside information (please complete the following information):**
 - Düncraft Version [031222a]

**Comment by Pingu-Pox** [comment]
This is a Rustic issue. I have removed Rustic from the upcoming build due to many other issues.

Fix available in next version.
