### ISSUE TITLE
ANCIENT WARFARE 2; NEEDS ITEMS TO STACK MORE

### ISSUE THREAD

**Issue by TroyTheGod55** [Pingu-Pox/duncraft#18]
The Research table only has an inventory of 9 slots for the input and all of the research requires more than 9 items
An example would be that researching invention requires 12 sticks, 4 torches, 3 string and 4 coal; with only the 1 item stack  limit on, it cant start to research with out all the necessary items to fulfill it

**Comment by TroyTheGod55** [comment]
Cannot progress with out research

**Comment by TroyTheGod55** [comment]
Never mind there is a button to use adjacent inventory....Damascus

**Comment by Pingu-Pox** [comment]
Mod removed
