### ISSUE TITLE
Can't make the railcraft cargo cart

### ISSUE THREAD

**Issue by TroyTheGod55** [Pingu-Pox/duncraft#19]
Trying to craft the railcraft cargo cart;
![image](https://user-images.githubusercontent.com/101856745/159069512-3f51f4ad-9fb7-4fd0-987a-e02b45c8dcb0.png)
it only can be made into chest cart from original minecraft
![image](https://user-images.githubusercontent.com/101856745/159069600-57c961a7-e2bc-4cad-b9f2-35c33fe5ed93.png)
Even when im using a trap chest which the railcraft recipe requires 
![image](https://user-images.githubusercontent.com/101856745/159069732-9252a572-197e-4bd2-8286-66a5be556c58.png)
![image](https://user-images.githubusercontent.com/101856745/159069793-c538781e-b710-4005-8972-5d7ac2858e67.png)

**Comment by Pingu-Pox** [comment]
Known issues from developer. Worked around it with custom recipes implemented with CraftTweaker2

EDIT: Available in next update
