### ISSUE TITLE
Overlapping Recipes

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#2]
**Describe the bug**
Soot and Railcraft have an overlapping recipe.

soot:wrought_tile (#11651)
railcraft:tank_iron_wall#0$2 (#4775/0)

Shared recipe is 4 iron plates in a 2x2.
There are 3 versions of the iron plate (railcraft, immersive engineering, embers) and all share the same recipe set, including this overlap.

This overlap prevents the player from crafting railcraft locomotive.

**Screenshots**
![image](https://user-images.githubusercontent.com/97805739/149645434-9d1e51cf-c8cc-437e-9551-5d863965f3a3.png)
![image](https://user-images.githubusercontent.com/97805739/149645441-731838da-78ec-4563-ab95-1991fbeeb1fd.png)

**Clientside information (please complete the following information):**
 - Düncraft Version [011322a]

**Comment by Pingu-Pox** [comment]
This has been fixed, and will be available in the next build.
