### ISSUE TITLE
Text in book overflowing - Tinker's Construct

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#20]
**Describe the bug**
The text in the book for Construct's Armory is overflowing, causing the left page to have words cut off, and the right page having words float off the page where there is not enough contrast to read.

![image](https://user-images.githubusercontent.com/97805739/159098483-163a1848-131a-446a-84f5-c1b1283ba4dd.png)

**Clientside information (please complete the following information):**
 - Düncraft Version [031222a]

**Additional context**
Book is "Materials and You - Armory Addendum (#7278)"
Noticed it with the Armory book, did not pay attention to the tool/weapon book to see if it too had the issue. 

GUI scale is set to Normal; changing GUI scale does not change text rendering.
![image](https://user-images.githubusercontent.com/97805739/159098635-c34132c5-b069-4f0b-9111-d5211a373149.png)

**Comment by Halfshot555** [comment]
The Materials and You V1 also has the overflow issue
![image](https://user-images.githubusercontent.com/97805739/159106235-2159a3c9-1853-4496-b597-e64ad280baf5.png)

**Comment by Pingu-Pox** [comment]
This is an issue with Optifine and the tinker's suite of mods. Since the actual release of Düncraft will not include Optifine, it will not be an issue... Stupid answer I know...

Reference: https://github.com/sp614x/optifine/issues/1394
