### ISSUE TITLE
Fishing Made Better - PAMs Recipes

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#21]
**Is your feature request related to a problem? Please describe.**
Fishing made better fish slices only have 2 recipes currently, FMB's Sushi and Cooked Fish Slice. I suggest trying to add these items to the PAM recipes that take raw and cooked fish.

![image](https://user-images.githubusercontent.com/97805739/159099220-eb0344c7-84c2-4f14-81e9-5c39d79807e1.png)

PAMs has 6 raw fish recipes and 12 cooked fish recipes

**Comment by Pingu-Pox** [comment]
Done
