### ISSUE TITLE
Railcraft Rolling Machine

### ISSUE THREAD

**Issue by TroyTheGod55** [Pingu-Pox/duncraft#22]
The Manual Rolling machine does not make the correct amount of items when crafting in it
what the recipe says
![image](https://user-images.githubusercontent.com/101856745/159338939-b50cbf63-ecac-4673-96ab-2f9c607ef517.png)
What it made
![image](https://user-images.githubusercontent.com/101856745/159339051-4a7ed14c-bfd3-4ba1-b632-ae91ca8cdec9.png)
Same goes for other items made in the machine such as plates

**Comment by Pingu-Pox** [comment]
Increased the stack size of the outputs and verified this fixes the issue.

Available in the next version.
