### ISSUE TITLE
mxTune Mod

### ISSUE THREAD

**Issue by TroyTheGod55** [Pingu-Pox/duncraft#23]
There are no recipes to make the Golden Bone or Timpanic Membrane
![image](https://user-images.githubusercontent.com/101856745/159349217-35bc9040-9dd8-46ba-b771-ba89c4fa2465.png)
![image](https://user-images.githubusercontent.com/101856745/159349251-e11f36d3-1402-4d53-bd0b-4770f97281c2.png)
and it is possible there are more uncraftables for this mod

**Comment by TroyTheGod55** [comment]
And when i try to look up a recipe for other instrument its is only giving me the recipe for the pan flute
![image](https://user-images.githubusercontent.com/101856745/159349555-df5d99a6-6998-47e4-94d4-73dcc8fd59ae.png)

**Comment by Pingu-Pox** [comment]
Golden bone and timpani membranes are mob drops.
Flute pan can be changed into any other instrument.

Individual instrument recipes can possibly be something I look at in the future.
