### ISSUE TITLE
Barley to Bread Recipe

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#24]
**Describe the bug**
Found that Barley has a direct recipe for crafting bread. Says recipe is from Natura
Listed for 3 forms from barley
-Natura
-Pams
-Bone Apple Tea

![image](https://user-images.githubusercontent.com/97805739/160019176-43d2099b-98b6-4f8f-937f-5ea41fcf6de3.png)

**Clientside information (please complete the following information):**
 - Düncraft Version [032422b]

**Comment by Pingu-Pox** [comment]
Removed recipe.

Available in next build.
