### ISSUE TITLE
Brew kettle not heating up correctly the fire flashes 

### ISSUE THREAD

**Issue by chadica** [Pingu-Pox/duncraft#25]
**Describe the bug**
The fire in the Brew kettle keeps flashing and sometimes it brews the ale and other times it doesnt

**To Reproduce**
Place the brew kettle down with fire underneath

**Expected behavior**
Not flashing and always brew with stuff in it

![2022-03-27_03 30 50](https://user-images.githubusercontent.com/73349571/160272104-256bce2f-9f13-4244-9e16-824e063f2fcd.png)

**Clientside information (please complete the following information):**
 - Launcher:  MultiMC
 - RAM allocated to java (8192and 9088)
 - Düncraft Version  032622a

**Comment by Pingu-Pox** [comment]
Please replicate this in single player in creative mode. I suspect server lag is to blame.

**Comment by Pingu-Pox** [comment]
Issue resolved with better fuel
