### ISSUE TITLE
Beeswax from growth craft to craft quark candle

### ISSUE THREAD

**Issue by chadica** [Pingu-Pox/duncraft#26]
**Describe the solution you'd like**
Turn the colored bees wax from growth craft into their quark candle counterpart by 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. This is where you'd suggest a different mod if you have one in mind.
![2022-03-27_03 52 32](https://user-images.githubusercontent.com/73349571/160272312-edde3849-883a-4363-8bc6-563cdd33ca03.png)

![2022-03-27_03 52 45](https://user-images.githubusercontent.com/73349571/160272314-2e8d10b3-7065-443c-b20c-c5af45fc35f1.png)

![2022-03-27_03 52 47](https://user-images.githubusercontent.com/73349571/160272317-78bc5696-420a-42aa-8ba4-2af4155ae4db.png)

**Additional context**

**Comment by Pingu-Pox** [comment]
Going to not implement this as I got to thinking, if I made a way to make candles from a different mod, that discourages the original method of making said mod's candles (and gathering of related resources).
