### ISSUE TITLE
Duplication Glitch - PAMS + Cooking with Blockhead

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#27]
**Describe the bug**
While crafting fresh water from purified water bottle, I decided to try placing it in the CWB system to craft it faster. It detected and performed the recipe, giving PAM's fresh water and an empty bottle. But after crafting awhile it didn't stop. So I checked the system and it didn't remove any of the purified water bottles.

**To Reproduce**
1. Place purified water bottle in Cooking with Blockhead inventory system (Kitchen Counter)
2. Open the CWB Cooking Table and look for the fresh water recipe.
3. Craft the fresh water
4. Observe that the water bottle is still in the CWB system.

**Expected behavior**
That CWB performs the crafting. But also removes the ingredient item.

**Clientside information (please complete the following information):**
 - Düncraft Version [032622a]

**Further Testing**
I have found duplication with the following other recipes
- Water Bottle + Pot into Salt (Duplicates the Pot and leaves behind water bottle for infinite crafting)
- Making Dough (Duplicates the Mixing Bowl)
- Grinding Flour using Mortar & Pestle (Duplicates Mortar & Pestle)
- Making Bread (Duplicates the Bakeware)

**Comment by Halfshot555** [comment]
After posting. I thought about the water->salt recipe and tested it with CWB. It also duplicates. But even worse. 

It keeps the water bottle in the CWB system. Keeps the PAMs Pot on the tool rack. and gives me a new pot, an empty bottle, and the salt.

So, duplicates pots, and doesn't remove the ingredient item (water bottle)

**Comment by Halfshot555** [comment]
Just had another tool duplication. Making dough consumed the 3 ingredients correctly, but duplicated a PAM's mixing bowl.

**Comment by Halfshot555** [comment]
Yet another. Grinding flour (Mortar & Pestle + Wheat) in the CWB system duplicates the Mortar & Pestle

**Comment by Pingu-Pox** [comment]
Fixed in next version.
