### ISSUE TITLE
Horse Carts

### ISSUE THREAD

**Issue by TroyTheGod55** [Pingu-Pox/duncraft#28]
Not sure if it is a bug or an unintended feature but, when a player opens the inventory of the horse cart that has an inventory, another player can then move the horse cart as far away as they want to and the first player can still sit there with the inventory open; so basically long distance instant transport of items;
possible abuse is likely if others find out

**Comment by Pingu-Pox** [comment]
Please test this scenario:
Thorbis opens cart inventory, Kyandar rides away to the village, Thorbis adds items, Kyandar takes items out, Thorbis adds more items, Kyandar takes more items out.

**Comment by Pingu-Pox** [comment]
Tested and broken. Removed the cart from future builds and opened ticket: https://github.com/MennoMax/astikor-carts/issues/81

**Comment by Pingu-Pox** [comment]
Updated to latest version of Astikor carts, that apparently fixes the issue. Please test in the next version.
