### ISSUE TITLE
Serene Seasons and Agricraft Compatibility 

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#29]
**Is your feature request related to a problem? Please describe.**
The Agricraft Crop Sticks do not adhere to the seasons added by Serene Seasons. Here is a compadtibility mod I have found that fixes the disparity. No more mass farming out of season.

https://www.curseforge.com/minecraft/mc-mods/agriseasons

**Comment by Pingu-Pox** [comment]
Added to next build.
