### ISSUE TITLE
Hunger Overhaul - Food Values

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#3]
### Describe the bug
I think something in our configs are making the food values come out inconsistent.

Looking through food options I noticed that some values don't make much sense. Mainly things that looks like they should be filling are giving only 2 points of hunger, while similar large crafting recipes still have 5+ hunger. I'll be using the **Chicken Dinner**, **Mashed Potatoes**, and **Fried Chicken** as examples. I'll be pulling base food values from https://harvestcraftmod.fandom.com/wiki/HarvestCraft_Wiki

From what I see in the client side config for Hunger Overhaul, it appears that it should be taking all base food values and dividing by 4 and saturation values divided by 20.

### Chicken Dinner
https://harvestcraftmod.fandom.com/wiki/HarvestCraft_Wiki
Wiki states 9 Hunger and 10.8 Saturation.
By math with HO, expected 2 (round down from 2.25) Hunger and 1 (round up from 0.54) Saturation.
In game we see this correctly as 2H 1S.
![image](https://user-images.githubusercontent.com/97805739/149674078-5db30702-283f-4c7d-b419-83b41a0f2035.png)

### Mashed Potatoes
https://harvestcraftmod.fandom.com/wiki/Mashed_Potatoes
This is an ingredient for the Chicken Dinner above.
Wiki states 9 Hunger and 10 Saturation.
Expected HO to change to 2 (2.25) H and 1 (0.5) S.
In game we don't see this change, instead it became 5H and 4S.
So something did change the values, but not sure what.
![image](https://user-images.githubusercontent.com/97805739/149674083-a2ddf7a3-1472-4e85-a639-5369b1952300.png)

### Fried Chicken
https://harvestcraftmod.fandom.com/wiki/Fried_Chicken
Wiki states 11 Hunger and 10 Saturation.
Expected HO to change to 3 (2.75) H and 1 (0.5) S
In game we see 7H and 5S.
So again, something did change its value, but unsure what.
![image](https://user-images.githubusercontent.com/97805739/149675485-e39431c3-03a0-4b1b-b528-c734012f7574.png)

### Clientside information (please complete the following information):
 - Düncraft Version [011322a]

### Additional Details
IMO, having the food values divide by 4 is too strong, and will possibly drive players to not bother crafting the stronger food items. If we go through the process of prepping multiple ingredients that are 1-2 hunger value themselves, only to get an output food that is 2-3 hunger points, that is not much gain for the effort and you are better off just eating the ingredients.

I suggest testing with a divide by 2 (half food value) as that will still give the larger food items a distinctive incentive to craft while still not fully satisfying player hunger alone.

**Comment by Halfshot555** [comment]
So i set my client side to divide by 2; **Chicken Dinner** updated as expected, but **Mashed Potatoes** and **Fried chicken** did not change values. So Hunger Overhaul is not applying changes to those food items.

![image](https://user-images.githubusercontent.com/97805739/149676323-a002f54c-9a5e-488d-b02f-6aa30a976c49.png)
![image](https://user-images.githubusercontent.com/97805739/149676327-00d5fbce-1ece-40e1-bc08-ebc0c2349acf.png)
![image](https://user-images.githubusercontent.com/97805739/149676334-9ff928c5-472c-41ce-b3c1-1d0fab949b9a.png)

**Comment by Halfshot555** [comment]
How to add a JSON to HO to force food/saturation values
https://github.com/progwml6/HungerOverhaul/wiki#custom-food-values

**Comment by Halfshot555** [comment]
I wrote a script to convert our sheet into the JSON for us. expected fields are
A: name without the <>
B: hunger value as an integer (a half food symbol in game is a value of 1)
C: saturation value as integer, same rule as for hunger. (there is a formula that derivies the saturation from the hunger, but I'll run math to get the expected saturation.)

**Comment by Pingu-Pox** [comment]
Resolved by Johannes and Halfshot in 0.0.2
