### ISSUE TITLE
Breeding Harnness

### ISSUE THREAD

**Issue by JohannesRamheart** [Pingu-Pox/duncraft#30]
**Describe the bug**
The breeding harnnes needs Jei fixes
![Capture](https://user-images.githubusercontent.com/102630179/160723430-b739d4ea-c56b-4f20-9541-90e0d12f838a.PNG)
![Capture](https://user-images.githubusercontent.com/102630179/160723526-394461f9-e03b-45b8-bb51-efeee97ed3c5.PNG)
![unknown2](https://user-images.githubusercontent.com/102630179/160723592-a4137104-20dd-42f9-85ce-e0b65f5a773b.png)
![unknown](https://user-images.githubusercontent.com/102630179/160723593-4fedbad1-a71e-4248-82fe-ffa89f973b82.png)
![Untitled](https://user-images.githubusercontent.com/102630179/160723715-fe6aebe1-51cf-4d8a-9074-59d50853944e.png)

this should be removed from shapeless 
![Capture](https://user-images.githubusercontent.com/102630179/160724067-2c78d292-21c1-4a22-bcdc-937e0f2e8da6.PNG)

![unknown2](https://user-images.githubusercontent.com/102630179/160723988-76b2251a-f363-4a8d-b96f-58b03f19bb50.png)

**Additional context**
Suggest using leather strips with string instead of leather hide for lead
![Capture](https://user-images.githubusercontent.com/102630179/160723858-08217456-f0e5-4a7a-9cdf-ba0b88fa437c.PNG)

**Comment by Pingu-Pox** [comment]
Fix available in next build
