### ISSUE TITLE
Cooking with Blockheads - Sink Interactions

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#31]
**List of Interactions tested with the CWB Sink**
- Does not serve as water source
- Can be filled with standard water from a water bucket
- Can remove a bucket of water from the sink
- Cannot be filled with purified water from a purified water bucket
- - It did remove the purified water from the bucket though. Possibly bug worthy, but a mistake that players will likely not attempt a 2nd time anyway.
- Provides water to recipes if sink has water present
- - Recipes do not consume water from the sink's internal tank storage. This is a bug as it should require the sink to be refilled for further crafting
- Crafting salt using the sink to provide water duplicates an empty bucket into player inventory

**Outcomes**
- Infinite water inside of sink
- Duplication of buckets using water based recipes via the sink

**Clientside information (please complete the following information):**
 - Düncraft Version [032922a]

**Comment by Pingu-Pox** [comment]
Fixed the behavior that dupe'd buckets. It's not built into the mod to subtract water from the sink when crafting with water> We're going to have to wait for [this feature.](https://github.com/ModdingForBlockheads/CookingForBlockheads/issues/358)
