### ISSUE TITLE
Cooking with Blockheads - Oven fuel issue

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#32]
**Describe the bug**
The CWB Oven is currently set to only accept PAM's Cooking Oil as fuel. This is acceptable, but the oven only accepts 1 unit of oil at a time and burns through it in about half a second and the oven does not auto pull more oil from the CWB mutliblock storage. This means that to cook anything, you have to have about 8 units of oil in your inventory and spam move it into the oven to keep it on.

**To Reproduce**
1. Place a CWB Oven
2. Add food to the oven
3. Use PAM's Cooking Oil as fuel
4. Attempt to keep the oven fueled as it cooks

**Expected behavior**
I expect to be able to cook using the oven without having to manually add multiple units of oil during the process.
I suggest either: 
- setting the Oven to draw oil from the multiblock storage (Not sure if this is even an option)
- setting oil to stack so the player can add enough to the oven to cook correctly

**Clientside information (please complete the following information):**
 - Düncraft Version [032922a]

**Comment by Pingu-Pox** [comment]
Re-allowed other burnables as fuel. This is not the last time you will see the oven being worked on, I will be adding fuel/patching bugs on the oven's fuel slot later on.
