### ISSUE TITLE
Mobs

### ISSUE THREAD

**Issue by Runeforger** [Pingu-Pox/duncraft#33]
**Describe the bug**

**To Reproduce**
1. Open crafting table
2. Craft axe and log together
3. See error

**Expected behavior**

**Screenshots**

**Clientside information (please complete the following information):**
 - Launcher: [e.g. Vanilla, MultiMC, Curse, etc.]
 - RAM allocated to java (MIN and MAX)
 - Java flags (if any)
 - Düncraft Version [e.g. mmddyyr or x.x.x]

**Additional context**
Mobs on the server aren't spawning

**Comment by Pingu-Pox** [comment]
Fixed with gamerule

Change is live in the server
