### ISSUE TITLE
Spruce logs from conquest does not work in immersive engineering coke oven 

### ISSUE THREAD

**Issue by chadica** [Pingu-Pox/duncraft#34]
**Describe the bug**
Cannot put spruce logs from conquest into the coke oven from immersive engineering
**To Reproduce**
Try to place the spruce logs in an immersive engineering coke oven

**Expected behavior**
Spruce log

**Clientside information (please complete the following information):**
 - Launcher: MultiMC
 - RAM allocated to java 8192 and 9088
 
 - Düncraft Version 032922a

**Comment by Pingu-Pox** [comment]
This is supposed to output <minecraft:charcoal> right?

**Comment by chadica** [comment]
Yes it is

**Comment by Pingu-Pox** [comment]
Added natural logs from conquest to the logWood oredict, and tested this fixes the recipe in the coke oven.

Live in the next version
