### ISSUE TITLE
Carry anything anywhere with carry-on

### ISSUE THREAD

**Issue by JohannesRamheart** [Pingu-Pox/duncraft#35]
**Describe the bug**
Picking up an item with the carry-on, and then holding R to put whatever it is into your tool pouch, like a chest or an animal or a smeltery control block, which can then be taken out at any time.

**To Reproduce**
1. Open crafting table
2. Craft axe and log together
3. See error

Thorbis was able to replicate it

**Expected behavior**
I expected not to go in my tool belt.

**Screenshots**

**Clientside information (please complete the following information):**
 - Launcher: [e.g. Vanilla, MultiMC, Curse, etc.]
 - RAM allocated to java (MIN and MAX)
 - Java flags (if any)
 - Düncraft Version [e.g. mmddyyr or x.x.x]

**Additional context**
Pocket Cockatrice

**Comment by Pingu-Pox** [comment]
Fixed in next version
