### ISSUE TITLE
Tinkers Armory tool belt carry on swap

### ISSUE THREAD

**Issue by JohannesRamheart** [Pingu-Pox/duncraft#36]
**Describe the bug**
Anything that you can carry w/ Carry-on can be swapped away to your tool belt.

**To Reproduce**
Shift right click entity or tile object in to hand
use tinkers belt mod switch {key} 
recrated by thorbis

**Expected behavior**

**Screenshots**

**Clientside information (please complete the following information):**
 - Launcher: [e.g. Vanilla, MultiMC, Curse, etc.]
 - RAM allocated to java (MIN and MAX)
 - Java flags (if any)
 - Düncraft Version [e.g. mmddyyr or x.x.x]

**Additional context**

**Comment by Pingu-Pox** [comment]
Fixed in the next update
