### ISSUE TITLE
FATAL ERROR FOR BETTER BUILDER'S WANDS AND TOOL BELT

### ISSUE THREAD

**Issue by TroyTheGod55** [Pingu-Pox/duncraft#37]
When removing a Better Builder's Wand from a Tool belt (a diamond one in this instance) from the Tool belt mod it causes a fatal error to crash to title screen from server
![image](https://user-images.githubusercontent.com/101856745/161426353-49f61767-fa44-43a8-86b0-49682d40097a.png)
When user tries to reconnect to server after this crash; a possible corrupted item(be it the tool belt or the builder's wand; unknown)the user displaces a "has joined" message in the chat and then proceeds to immediately crash again with the same error message, before ever loading back into the server completely; once this user tries to load back into the server with this bug  others who are on the server also crash to title screen with same error, but the others can reconnect normally after the crash without the problem person loading in 
https://paste.ee/p/FWpkn
My character is now unable to log back into the server without crashing my client to title screen and possibly crashing others who are on the same time i try to load in with this bug.

**Comment by Pingu-Pox** [comment]
Leaving this one open until we're an update ahead of alpha 6.

**Comment by Pingu-Pox** [comment]
Closing due to being unable to replicate.
