### ISSUE TITLE
Conquest Plaster with Red Masonry lines corner block

### ISSUE THREAD

**Issue by TroyTheGod55** [Pingu-Pox/duncraft#38]
This block when placed down has a yellow piss color to it when the picture says it is supposed to be white
![image](https://user-images.githubusercontent.com/101856745/161464760-24ccf260-ec2c-4643-96c3-0163effe513e.png)
![image](https://user-images.githubusercontent.com/101856745/161464862-a7c233a8-19c5-4b28-aa42-f9e9c67e494c.png)

**Comment by Pingu-Pox** [comment]
Can't reproduce, might have been to lagging lighting updates on the server.
