### ISSUE TITLE
Tinkers and ice and fire addon mods to look at and the vault hunters modpack

### ISSUE THREAD

**Issue by chadica** [Pingu-Pox/duncraft#39]
Tinker's addon
https://www.curseforge.com/minecraft/mc-mods/armory-expansion

https://www.curseforge.com/minecraft/mc-mods/armory-expansion-bits-and-pieces

Ice and fire addon
https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-tweaker

Modpack
https://www.curseforge.com/minecraft/modpacks/vault-hunters-official-modpack

**Comment by chadica** [comment]
Login protection mod
https://www.curseforge.com/minecraft/mc-mods/logimmune

**Comment by chadica** [comment]
Nether ores
https://www.curseforge.com/minecraft/mc-mods/nether-metals

**Comment by chadica** [comment]
Wizard mod to try on reset?
https://www.curseforge.com/minecraft/mc-mods/wizardry-mod

**Comment by Pingu-Pox** [comment]
> Login protection mod https://www.curseforge.com/minecraft/mc-mods/logimmune

added

**Comment by Pingu-Pox** [comment]
> Nether ores https://www.curseforge.com/minecraft/mc-mods/nether-metals

Skipped

**Comment by Pingu-Pox** [comment]
> Ice and fire addon
https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-tweaker

Skipped as it's not available for 1.12.2

**Comment by Pingu-Pox** [comment]
> Tinker's addon
https://www.curseforge.com/minecraft/mc-mods/armory-expansion
https://www.curseforge.com/minecraft/mc-mods/armory-expansion-bits-and-pieces

added

**Comment by Pingu-Pox** [comment]
> Modpack
https://www.curseforge.com/minecraft/modpacks/vault-hunters-official-modpack

Skipped
