### ISSUE TITLE
Chunk Claiming tool shows a map

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#4]
**Describe the bug**
The chunk claiming tool in the top left of inv opens a map that has enough detail to tell player location.

**Screenshots**
![image](https://user-images.githubusercontent.com/97805739/149682338-7605a95b-6713-4a28-ac48-c5f40dc20bf5.png)
![image](https://user-images.githubusercontent.com/97805739/149682330-8fe70b50-c902-42fa-ac7a-4e5ad15c529d.png)

**Clientside information (please complete the following information):**
 - Düncraft Version [011322a]

**Comment by Pingu-Pox** [comment]
Removed the client-side ability to view chunk-claiming. Going to see about making this an OP feature. Allowing chunk-claiming this way unfortunately exposes the map.
