### ISSUE TITLE
Mine Colonies - Can't make town hall.

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#41]
**Describe the bug**
Mine Colonies Town Hall is the starting point of the mod. Normally the mod has you acquire it by building Supply Camp or Supply Ship, but it appears that those have been disabled as JEI does not show recipes. Instead the town hall is showing a recipe, but attempting to craft it fails.

**To Reproduce**
JEI Recipe
![image](https://user-images.githubusercontent.com/97805739/163688279-a43b325b-e2e8-4fd7-b88e-f52d17bbec93.png)
In crafting table with minecraft:planks as wood.
![image](https://user-images.githubusercontent.com/97805739/163688297-de8d313c-7de6-44da-8e22-3a8ac48c2d9f.png)

**Expected behavior**
JEI to allow you to craft the recipe if it shows recipe, if there is some knowledge/quest blocker maybe somehow block the recipe from showing.

**Clientside information (please complete the following information):**
 - Düncraft Version [0.0.1]

**Additional context**
Also, I've noted that the other MineColonies blocks (mine/warehouse/etc) accept the other wood types (forresty/binnies/conquest) but the town hall JEI is only rotating through the vanilla planks.

**Comment by Pingu-Pox** [comment]
Must craft supplychest/ship first (undoc'd 4x4 recipes)
