### ISSUE TITLE
Crash when right-clicking @conquest rocks when they are adjacent to @betterwithmods slabs

### ISSUE THREAD

**Issue by Seether18** [Pingu-Pox/duncraft#43]
**Describe the bug**
I right clicked on a conquest reforged rock

**To Reproduce**
Right click on conquest reforged 

**Expected behavior**
Kicks me out of the server

**Screenshots**
![image](https://user-images.githubusercontent.com/23374551/163726299-bd03a4b9-8515-449b-aca5-d69e65c367a3.png)

**Clientside information (please complete the following information):**
 - Launcher: [e.g. Vanilla, MultiMC, Curse, etc.]
 - RAM allocated to java (MIN and MAX)
 - Java flags (if any)
 - Düncraft Version [e.g. mmddyyr or x.x.x]

**Additional context**

**Comment by Pingu-Pox** [comment]
We have identified an issue with these rocks being on/near @betterwithmods slabs. Researching further, but it just gives me more reason to remove @betterwithmods (really no skin off anyone's back aside from the windmill/water wheels, which partially are replaced by @horsepower's mechanics)

**Comment by Pingu-Pox** [comment]
Removed @betterwithmods, problem no longer able to replicate the issue.

Live in next build.
