### ISSUE TITLE
Pine Log / Plank not converting properly 

### ISSUE THREAD

**Issue by lockerbyy** [Pingu-Pox/duncraft#46]
![image](https://user-images.githubusercontent.com/104037221/164109609-8dabb7e5-fa1d-4941-8ecb-91e40e6c7b72.png)
![image](https://user-images.githubusercontent.com/104037221/164109805-bf07d137-7866-4d0a-b535-ea3748ea8d14.png)
![image](https://user-images.githubusercontent.com/104037221/164109829-654f504e-3f91-470c-97d4-467f4ec5ed38.png)

all are not converting via right click axe . Will convert via crafting menu

**Comment by Pingu-Pox** [comment]
All three now convert properly and will be live in the next update.
