### ISSUE TITLE
Geolosys Spawning - Conquest blocks not in config

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#47]
**Describe the bug**
While trying to mine for a geolosys copper vein, i found 2 separate veins that i failed to locate copper between surface and bedrock. while investigating why this might be, I found that the current config for geolosys is missing the conquest blocks, where they were present in the previous config.

With current gen setting geolosys ore will only be replacing the vanilla rocks that spawn just under surface and around bedrock layer.

0.0.1 config
![image](https://user-images.githubusercontent.com/97805739/164146400-ee1720e7-aa37-40ca-b29f-ecaa76d08e3a.png)

040322b config
![image](https://user-images.githubusercontent.com/97805739/164146428-ce087a1b-7c4d-4c5a-8b89-60fa0d116ff6.png)

**Clientside information (please complete the following information):**
 - Düncraft Version [0.0.1]

**Comment by Pingu-Pox** [comment]
Definitely an oversight when we reset Geolosys. Nice catch.

Live in next version.
