### ISSUE TITLE
To allow incompatible enchantments to generate in when doing the quark enchanting

### ISSUE THREAD

**Issue by chadica** [Pingu-Pox/duncraft#48]
**Is your feature request related to a problem? Please describe.**
When i enchanted my diamond mesh it game me sieve luck of the sea which doesn't allow to have sieve luck on it because they are incompatible 
**Describe the solution you'd like**
Changing 
How much to multiply the frequency of pieces where incompatible pieces have been generated    D:"Incompatible Multiplier"=0.0
to
How much to multiply the frequency of pieces where incompatible pieces have been generated
   D:"Incompatible Multiplier"=9.0 ,or lower

**Describe alternatives you've considered**
Another way if we can get ride of sieve luck of the sea

**Comment by Pingu-Pox** [comment]
Should be able to remove this enchant from the pool. May I ask why?

**Comment by chadica** [comment]
I just thought that you wanted to keep fishing to just fishing because if you have sieve luck of the sea it has a chance to product fish

**Comment by Pingu-Pox** [comment]
You're correct. It likely only produces fish that don't obey fishingmadebetter's ruleset either.

**Comment by Pingu-Pox** [comment]
Disabled enchantment.

Live in next version.
