### ISSUE TITLE
Smashing log with hammer does not give wood chippings

### ISSUE THREAD

**Issue by chadica** [Pingu-Pox/duncraft#49]
**Describe the bug**
Mining a log with a ex nihilo hammer or tinkers sledge hammer with will not give wood chippings it give nothing

**To Reproduce**
Mine a log with a ex nihilo hammer

**Expected behavior**
It suppose to give you wood chippings but does not

**Clientside information (please complete the following information):**
 - Multimc
 - 8000-9000
 - Düncraft 0.0.2

**Additional context**
Reason for this is because its a good way to get dirt without having to tear up the land

**Comment by Pingu-Pox** [comment]
Fixed in 0.0.4
