### ISSUE TITLE
Conquest plaster

### ISSUE THREAD

**Issue by TroyTheGod55** [Pingu-Pox/duncraft#50]
![image](https://user-images.githubusercontent.com/101856745/165895723-0212049b-f1ae-4e0c-b7fb-a27bdeab3d37.png)
This clean white plaster crafting recipe requires specifically an iron bucket filled with water; would like to use other buckets as well for the crafting of it

**Comment by TroyTheGod55** [comment]
Possible other recipes require specific items that can be substituted as well

**Comment by Pingu-Pox** [comment]
Can't fix this with an oreDict tweak, so it would need to be fixed on a case-by-base basis. I assume you want the @notreepunching ceramic Bucket (Water) and the @ceramics Water Clay bucket to be used as a sub-in for the @minecraft water bucket? There are 25 recipes in conquest that use @minecraft water buckets.

**Comment by Pingu-Pox** [comment]
If so, live in 0.0.4
