### ISSUE TITLE
Add BBQ Jackfruit Recipe

### ISSUE THREAD

**Issue by lemonelda** [Pingu-Pox/duncraft#51]
**Is your feature request related to a problem? Please describe.**
There are many recipes for BBQ Jackfruit but the recipe does not exist in the mod.

**Describe the solution you'd like**
A recipe for BBQ Jackfruit to be implemented.

![bbqjackfruit](https://user-images.githubusercontent.com/103978884/166091914-caf6772c-f70d-4b76-b106-e2d2c1de5230.png)

**Comment by Pingu-Pox** [comment]
Fixed and coming in 0.0.4
