### ISSUE TITLE
Stockpile Duplication Glitch

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#52]
**Describe the bug**
Not sure what all items are effected, but I initially noticed with redstone. Removing redstone using shift leftclick deposits a unit directly to inventory while also popping an item into the world, thus creating a 2nd unit of redstone.

**To Reproduce**
1. Place 1 unit of redstone into a stockpile.
2. Left Click remove redstone.
3. See 1 unit of redstone removed.
4. Place 1 unit of redstone into a stockpile.
5. Shift Left Click remove the redstone.
6. See 1 unit of redstone in inventory, and a 2nd dropped into world.

**Clientside information (please complete the following information):**
 - Düncraft Version [0.0.2]

**Effected Items**
- Redstone
- Redstone Block

**Comment by Pingu-Pox** [comment]
Wizardry is to blame, and has been removed in the next build due to annoyance.
