### ISSUE TITLE
Bay window

### ISSUE THREAD

**Issue by TroyTheGod55** [Pingu-Pox/duncraft#53]
![image](https://user-images.githubusercontent.com/101856745/166129505-edcbe3f8-b663-4068-93b2-858cde4e852c.png)
Would like a recipe for this bay window
something like:
[glass plane][stick][glass plane]
[glass plane][stick][glass plane]
[glass plane][stick][glass plane]

**Comment by Pingu-Pox** [comment]
Live in 0.0.4
