### ISSUE TITLE
Thaumcraft - Crucible - Shift Right Click

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#54]
**Describe the bug**
Doing Thaumcraft, to empty a crucible (so as to move onto another recipe or reset contents) you need to shift right click with an empty hand. This is currently being detected by the mod that lets us pick up blocks.

**Expected behavior**
Let the player clear the Crucible instead of picking it up.

**Clientside information (please complete the following information):**
 - Düncraft Version [0.0.2]

**Additional context**

**Comment by Pingu-Pox** [comment]
Fixed in 0.0.4
