### ISSUE TITLE
Thaumcraft - Cannot finish Hedge Alchemy - Known error in Thaumcraft

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#55]
**Describe the bug**
One of the research items in the thaumonomicon to progress in alchemy requires you to craft cobwebs. Issue is that this version of thaumcarft has a known error in this recipe which makes it impossible to perform.

![image](https://user-images.githubusercontent.com/97805739/166170866-ff8fc53f-efdc-4a6c-9343-63c1acfc77e3.png)
![image](https://user-images.githubusercontent.com/97805739/166170829-81d9ca84-f696-4163-9c76-fc84d61c06eb.png)

Link to error reported in the Thaumcraft git.
https://github.com/Azanor/thaumcraft-beta/issues/1605

**Clientside information (please complete the following information):**
 - Düncraft Version [0.0.2]

**Comment by Pingu-Pox** [comment]
Try this fix in single-player. I don't know how to do Thaumcraft, so it will be faster for you to try this. If you need help preparing the modified version of Thaumcraft, let me know.

**Comment by Halfshot555** [comment]
I performed the JSON edit to remove the offending recipe and it worked. Also finished that step to confirm if anything else was blocking Hedge Alchemy.

![image](https://user-images.githubusercontent.com/97805739/167203401-6671a593-b45c-4124-9ec2-f8158453c32d.png)

**Comment by Pingu-Pox** [comment]
Thank goodness you could tell what fix I referenced as I failed to provide the link to the post in their ticket. Can this fix be put in a resourcepack or does it need to go in a modified jar?

**Comment by Pingu-Pox** [comment]
Thank you for fixing this Kyandar!

**Comment by Pingu-Pox** [comment]
Managed to "fix" this without needing to patch the jar using Crafttweaker and Modtweaker. The journal still requires the web to be made for that chapter, and it still doesn't show how to make it, but I added a tooltip explaining how to make it.
