### ISSUE TITLE
Thin ice/No punch trees

### ISSUE THREAD

**Issue by JohannesRamheart** [Pingu-Pox/duncraft#56]
![Untitled](https://user-images.githubusercontent.com/102630179/166391774-7d1f0ddf-f04d-44eb-a022-0c2f73579d15.png)

Breaking down logs on ices doesn't work

**Comment by Pingu-Pox** [comment]
This is an issue with @notreepunching, not Düncraft. Please report the bug here: https://github.com/alcatrazEscapee/no-tree-punching/issues

...as it occurs with no other mods present.
