### ISSUE TITLE
Conflicting recipire forestry/conquest

### ISSUE THREAD

**Issue by TroyTheGod55** [Pingu-Pox/duncraft#57]
![image](https://user-images.githubusercontent.com/101856745/166588288-090646df-b7e8-459c-b649-eafc757a5bae.png)
this recipe is conflicting with a conquest recipe
![image](https://user-images.githubusercontent.com/101856745/166588342-bf983e49-7cb7-41b1-bf2e-66dcf7ee582c.png)
log piles are used to make large batches of charcoal by covering them with specific covers to increase thier output

**Comment by TroyTheGod55** [comment]
https://ftb.fandom.com/wiki/Wood_Pile here is more info for it

**Comment by Pingu-Pox** [comment]
Fixed and coming in 0.0.4
