### ISSUE TITLE
Bronze ingot - Conquest coin texture

### ISSUE THREAD

**Issue by JohannesRamheart** [Pingu-Pox/duncraft#58]
![image](https://user-images.githubusercontent.com/102630179/167143954-9dc792d9-6114-46d8-9be5-5e735b232bb3.png)

**Comment by Pingu-Pox** [comment]
Appears to be an issue with changing resourcepacks at run-time. Might be an issue with my change to prefer geolosys ingot textures over other mods. To be safe, I will be removing this change in the next build as it was a personal preference change that is the only thing I can think of that would affect this particular issue (and shouldn't be related to resource packs at all tbf. I will wait for others to test this, and report to back to me in the meantime.
