### ISSUE TITLE
Compressed Mobs can be spotted through blocks

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#59]
**Describe the bug**
Was wandering in caves and noticed a white/gray line that when I zoomed in on revealed itself to be a compressed spider in a nearby cave.

![image](https://user-images.githubusercontent.com/97805739/167227684-77db4578-55aa-4e62-8a54-ca9fe2ae9de2.png)

**Clientside information (please complete the following information):**
 - Düncraft Version [0.0.3]

**Comment by Pingu-Pox** [comment]
Intended
