### ISSUE TITLE
Atlas - Map shows land/swamp for area with open water.

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#6]
**Describe the bug**
I'm unsure what the actual biome I'm observing is, but it looks like the Atlas is claiming it to be land, or possibly swamp.

I'd expect that an area with this much open water to be marked in the map as water instead of land.

**Screenshots**
![image](https://user-images.githubusercontent.com/97805739/149684991-9c14e11e-33cb-4d75-bb6c-bf25aab2b11f.png)
![image](https://user-images.githubusercontent.com/97805739/149685004-2c487bee-10ef-4a66-b331-82ecd6b72c91.png)

**Clientside information (please complete the following information):**
 - Düncraft Version [011322a]

**Comment by Pingu-Pox** [comment]
Can you provide me with the seed and coordinates of this biome if you still have all that on-hand?

**Comment by Pingu-Pox** [comment]
Definitely an unintended mod interaction. Antique Atlas has tagged that biome as "grassland" because of the dirt that lines the bottom of the body of water. Conquest Reforged has many custom biomes, and this is just one of many that were made without considering how other mods would handle it.
