### ISSUE TITLE
Wrong textures in Red Desert Biome

### ISSUE THREAD

**Issue by TroyTheGod55** [Pingu-Pox/duncraft#60]
![image](https://user-images.githubusercontent.com/101856745/167315366-bee6598e-5adb-4f21-b19b-b3c7f08b0ec5.png)
Brown dry clay has a column like texture that doesn't fit as a natural block
same with these dead shrubs and these are in the Red Desert Biome

**Comment by Pingu-Pox** [comment]
This is a bug with Optifine enabled.

**Comment by Pingu-Pox** [comment]
Conquest will not fix this, so it's up to us to fix or look passed.
