### ISSUE TITLE
Smeltery level bypass using Hopper and Redstone

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#61]
**Describe the bug**
Hoppers and redstone inputs can be used to bypass levels using the smeltery. This lets you interact with melter/smelters that are already placed, as you cannot place the blocks without the required level.

**To Reproduce**
I placed blocks in creative, then entered survival to verify that I couldn't directly interact.
![image](https://user-images.githubusercontent.com/97805739/167736543-2237c720-e770-4fbb-a930-844528018e45.png)

**Expected behavior**
I see this in 2 lights. 
- On one hand, this is an intended feature in tinkers for automation (hopper smelt and redstone clock to pour), and in order for someone to do it with existing lockout they need someone with the skill level to build/place the main blocks. 
- But on other hand, this is technically subverting the level requirement of using the smelter.

**Clientside information (please complete the following information):**
 - Düncraft Version [0.0.4]

**Comment by Pingu-Pox** [comment]
The use of redstone is an oversight. Do you have any suggestions on what to do about this?

**Comment by Halfshot555** [comment]
With the theme of the pack not really being inductive to large scale processing/automation, I think finding a way to disable the redstone inputs would be valid. I believe the intended use of the input was when a player was smelting multiple hundreds and wanted to empty, or to automatically funnel into another process (saw this in previous build by doubling iron in High forge then transferring to smeltery via channel)

Because of the small quantities and the smelter's main purpose moving to ingot/block and limited casting, automation isn't really needed for it.

**Comment by Pingu-Pox** [comment]
To disable redstone from interacting with the faucets, we will need to look at modifying this file: https://github.com/SlimeKnights/TinkersConstruct/blob/c01173c0408352c50a2e8c5017552323ce42f5b4/src/main/java/slimeknights/tconstruct/smeltery/block/BlockFaucet.java#L89

Lines 89 - 114

Seeing as this a code-related fix, it is getting put on the back-burner.

In the meantime, we can look at locking redstone behind metallurgy (and optionally more skills) as well.
