### ISSUE TITLE
Astikor Carts - Player pulling

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#63]
I tested in SP player pulling and how it interacts with the "speedModifier" config.
To add the player to pull carts, its just adding "minecraft:player" to the entity list in the config (each cart has own config group, so can say player can only pull cargo but not mob&plow)

It turns out though that the speed modifier does not behave as intuitive as first thought. Instead of being a passive speed decrease, its an active "walk" mode for the animals pulling the carts triggered by the sprint key. Even when I set the modifier to -0.9 the player still pulled the cart at standard walk/run speed. But the horse I was testing with would pull at its standard speed until you press the sprint key, which then applies the modifier, making it walk at -0.9 speed. The default config is -0.65 which makes it slightly slower than walking player; distance player covered in 3s, horse at -0.65 covered in 4.3s

That said, my suggestion would be that player pulling is acceptable, player still moves slower than horse and consumes food/water for movement thus causing the player to want to acquire an animal to pull anyway, especially for long distances.

**Comment by Pingu-Pox** [comment]
So your suggestion is simply to allow minecraft:player on the three cart canPull lists?

**Comment by Halfshot555** [comment]
There are 3 carts; Cargo, Mob (2 seat transport), and plow. My opinion is that if it is enabled for player to pull, yes to cargo, maybe to transport (rickshaw), but plow is a no (leave it to draft animals to plow the field)

**Comment by Pingu-Pox** [comment]
Done. Live in 0.0.5
