### ISSUE TITLE
any color harden clay in cabinet recipe :Pams:

### ISSUE THREAD

**Issue by JohannesRamheart** [Pingu-Pox/duncraft#64]
<cookingforblockheads:cabinet>
<minecraft:hardened_clay>
<minecraft:stained_hardened_clay:14>
<minecraft:stained_hardened_clay>
<minecraft:stained_hardened_clay:1>
<minecraft:stained_hardened_clay:4>
<minecraft:stained_hardened_clay:12>
<minecraft:stained_hardened_clay:15>
![cabinet](https://user-images.githubusercontent.com/102630179/167982188-56604cae-596f-48ef-987d-aa6f092311c4.png)

Making any colored clay craft into "<cookingforblockheads:cabinet>"
![unknown](https://user-images.githubusercontent.com/102630179/167981865-ce27b0cf-329a-45eb-b365-bbd21ab42529.png)

**Comment by Pingu-Pox** [comment]
Live in next version
