### ISSUE TITLE
Mine Colonies - Builder needs 'Unknown' tool

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#65]
**Describe the bug**
The minecolony builder is requesting a tool of unknown type (suppose to be pic/shovel) and even with me clearing the whole build area it still thinks it needs the tool.

**Screenshots**
Message of needing tool:
![image](https://user-images.githubusercontent.com/97805739/168447587-25168ef0-8e68-432c-95ff-dbd8784676b6.png)

Cleared Area:
![image](https://user-images.githubusercontent.com/97805739/168447580-a23c46d7-cd81-40e7-ad2d-d253c5feb458.png)

**Clientside information (please complete the following information):**
 - Minecolony Version: 1.12.2-0.11.841-ALPHA
 - Düncraft Version [0.0.4]

**Additional context**
Looking at some of the issues in the minecolony git, this seems to be a known issue that they fixed in their 1.15 builds, but never got a fix working in the 1.12 builds, and they stopped supporting 1.12.2. There are some reports from people claiming that downgrading to minecolonies-1.12.2-0.11.811-BETA-universal might work, I'll attempt to download and test the older version.

**Comment by Halfshot555** [comment]
Loaded a copy of the 0.0.4 pack with the 0.11.811-BETA minecolony and it fixes the issue
![image](https://user-images.githubusercontent.com/97805739/168448070-3f15fbe4-ee26-485d-bdab-064be37543f6.png)

**Comment by Pingu-Pox** [comment]
Downgraded Minecolonies for next build
