### ISSUE TITLE
Advanced Fishing - Spookyfin might be unobtainable

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#66]
**Describe the bug**
One of the fish added by Advanced Fishing, the spookyfin, that is descaled to get ghast tears might not be obtainable. According to the mod's curseforge and RLCraft wiki, the fish is suppose to be acquirable in biomes with the 'dead' tag, but mod page says this tag doesn't exist in vanilla biomes and must be present in mod biomes to be used. 

I don't know how to check the conquest biomes to see if this tag is assigned to any. But also, while checking configs, I couldn't find an entry for this fish. The other 2 fish assigned to 'dead' biomes are present in the config/fishingmadebetter/fishdata/advancedfishing.json but there is no entry for the spookyfin, possibly making it impossible to catch if there are no locations defined.

2 Things to check:
- Are there any biomes in conquest that contain the 'dead' tag.
- Is an entry in the config required to catch.

**Clientside information (please complete the following information):**
 - Düncraft Version [0.0.4]

**Comment by Pingu-Pox** [comment]
Added the spookyfin as a fish to possibly hook while fishing in lava in nether or creeping nether biomes. A quick warning though, I was unable to load my test world after making the change, but was able to make a new one and test. If this prevents people from loading into the server after the build, we will have to save this change for a server reset.
