### ISSUE TITLE
Debarking log recipe - possible recipe conflict

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#7]
**Describe the bug**
Combining axe + log looks to have 2 overlapping recipes.
-Debarked Log
-3x plank

**To Reproduce**
![image](https://user-images.githubusercontent.com/97805739/158491826-3c86d522-5d5e-4cfa-9596-c7a5e7847716.png)
![image](https://user-images.githubusercontent.com/97805739/158491848-0d1a1998-2a32-4b03-b8d1-b504d475b338.png)

**Clientside information (please complete the following information):**
 - Düncraft Version [031222a]

**Comment by Pingu-Pox** [comment]
Removing Debark mod in next version
