### ISSUE TITLE
Broad Axe Head can't be crafted. 

### ISSUE THREAD

**Issue by TroyTheGod55** [Pingu-Pox/duncraft#75]
Un able to make a Broad Axe head as it requires 8 materials to craft and the stack limit on them is preventing it from crafting.

![image](https://github.com/user-attachments/assets/7bf7e5c1-6212-4e9a-8fbf-53507a6fb13c)

If left as is people are unable to make the tier 2 tinker's tools.

Requesting cobble to stack at at least 4 to overcome this.

**Comment by Pingu-Pox** [comment]
Is this still an issue if you use two wood blocks as materials to fulfill the material cost? This is not an issue at the smeltery for metal parts.

**Comment by Pingu-Pox** [comment]
For now, just use logs to get the template piece. If you want stone parts that cost more than 4, I will need to look into that separately.
