### ISSUE TITLE
Thaumcraft

### ISSUE THREAD

**Issue by Bembul-Bristlebraids** [Pingu-Pox/duncraft#76]
**Describe the bug**
When researching in the research table it seems that some theories require more than one piece of paper in them to be able to finish the theory and make progress.
**To Reproduce**
1. Open Research table
2. conduct research until you get to a point where something seems to require more than one sheet of paper in the paper station.  Example the Celestial studies 
3. unable to select this option

**Expected behavior**
to select that path for the research, and it to complete the theory.

**Screenshots**
![image](https://github.com/user-attachments/assets/66010397-395a-42ea-9467-b65bb21ac84f)

**Clientside information (please complete the following information):**
 - MultiMC
 - Min-4096mib Max- 8192mib
 - Java flags Unsure
 - Düncraft Version 0.0.4

**Additional context**

**Comment by Bembul-Bristlebraids** [comment]
This may not be an actual bug I found something that I can try at some point to see if it fixes my issue. If it works ill make  a comment and mark it as solved.

**Comment by Pingu-Pox** [comment]
What's the most amount of paper needed for a single action in this context?

**Comment by Bembul-Bristlebraids** [comment]
Normally you only need one, but I have reason to believe now that I may
just need a thaumometer first then scan the sky for it and that might be
why it isn't working I just haven't had time to go creative mode and test
it yet

**Comment by Pingu-Pox** [comment]
Let me know your findings. If we need to make paper stack up to a higher count, I can make that happen, but only if required.

**Comment by Bembul-Bristlebraids** [comment]
Aye Capt I'll test it out tonight and report my findings

**Comment by Bembul-Bristlebraids** [comment]
ok so looks like i was right i need bot the thaumometer and the corisponding notes this is not a bug i jsut dont have all the things i need it also only needs the one sheet of paper. I am also unsure how to mark this as completed i do not see an option for that

**Comment by Pingu-Pox** [comment]
I gotchu!
