### ISSUE TITLE
LoD Sighting

### ISSUE THREAD

**Issue by JohannesRamheart** [Pingu-Pox/duncraft#79]
![image](https://github.com/user-attachments/assets/849cc0a1-6e96-4f2f-aa96-30c6b9848482)

Long lost remnant of Lords of Dünhiem on the discord activity mod.

**Comment by Pingu-Pox** [comment]
I'll add that LoD is mentioned in the main menu as well, should probably fix it everywhere.

**Comment by Pingu-Pox** [comment]
Fixed for next build.
