### ISSUE TITLE
Debarked Log only fuel

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#8]
**Describe the bug**
Debarked log from [Debark] can only be used as fuel, no other use ie. planks.

**To Reproduce**
![image](https://user-images.githubusercontent.com/97805739/158492009-4e570609-c581-43f7-bfee-ce1febf4e073.png)

**Expected behavior**
To have similar use to normal logs

**Clientside information (please complete the following information):**
 - Düncraft Version [031222a]

**Comment by Pingu-Pox** [comment]
Removing Debark mod in next version
