### ISSUE TITLE
Conquest Reforged Campfire - Can't finish crafting

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#9]
**Describe the bug**
The below recipe shows as a valid recipe but when trying to remove the item as output it does not given item and resets all the ingredients to the crafting slots

**To Reproduce**
![image](https://user-images.githubusercontent.com/97805739/158492211-ee75d9ae-5e00-4fff-bc5d-d85daeebd303.png)

**Expected behavior**
To either craft the item, or if invalid recipe not show an output item.

**Clientside information (please complete the following information):**
 - Düncraft Version [031222a]

**Comment by Pingu-Pox** [comment]
Was unable to replicate this in single player, but was able to on the server. Made a new recipes for the campfire, will check for ticket closure AFTER update.

**Comment by Pingu-Pox** [comment]
Fixed in alpha3
